spring:
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      import-check:
        enabled: false
  application:
    name: demo
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    h2:
      console:
        enabled: true
        path: /h2-console

camunda.bpm.admin-user:
  id: admin
  password: admin

